version: '3.9'
services:
  mern:
    build: .
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: production
    links:
      - db
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: mongo-db
    restart: always
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
